title: Chen Yubo的博客
description: >-
  Wubba Lubba Dub Dub! 探索无限维度的技术博客
baseurl: ""
url: "https://chenyubo123.github.io"
github_username: chenyubo123

theme: minima
plugins:
  - jekyll-feed

header_pages:
  - about.markdown
