title: 陈宇博的博客
description: >-
  记录技术探索，分享学习心得，发现无限可能
baseurl: ""
url: "https://chenyubo123.github.io"
github_username: chenyubo123

theme: minima
plugins:
  - jekyll-feed

header_pages:
  - about.markdown
